### ISSUE TITLE
Initial Plans and TODO list

### ISSUE THREAD

**Issue by blueluke** [blueluke/lotrdb#1]
## Bugs
- [x] Attachment panel does not collapse on click.
- [x] Remove links to prevent issues with decksaving?
- [x] Fix wrong button position in the saved decks panel with very long decknames.
## Misc
- [x] Merge upstream/master and implement the new additions.
- [x] Cleaning up the style.css (removing obsolete stuff)
## Design
- [x] New cardtype icons?
- [x] New sphere icons?
## Mobile
- [x] Auto-collapse the navbar.
- [x] Disable collapse animations on mobile devices (causes minor stutter/lag).
## Cardlist and deckview
- [x] Implementing basic column layout.
- [x] Move filters and search to panels.
- [x] Decklist and cardlist in panels
- [x] Card number buttons: Buttongroups? Just a single button?
- [x] Changing button color and style.
- [x] Adjust position of the new buttons.
## Suggested cards
- [x] Implement a new UI.
- [x] ~~Temporarily hides/replaces the cardlist?~~ A seperate tab works better.
## Decklist panel
- [x] ~~Big screens: Expands heroes/allies/etc panels by default.~~
- [x] Reducing spacing, margins and size of the decklist.
## Cardpreview
- [x] Implementing a popup modal
- [x] ~~Trigger on hover or long click?~~ Trigger on basic click.
## Pack overview
- [x] Implementing a grid layout.
- [x] Structure with panels? ~~Or move to modal popup window?~~
- [x] Select forms instead of button grid. 
## Decks
- [x] Form panel ~~or table?~~
- [x] Adding glyphicons to the buttons.
- [x] Smaller (icon-only) buttons for small devices.
## About
- [x] Merging Help and Updates into a new **About** page.
- [x] Hide decklist column.
- [x] Or add a (dismissable) alert with instructions to each page instead? 
## Stats
- [x] Grid layout with panels.
